name: C/C++ Build and Check Health

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v2
    
    # Set up Docker and build your image
    - name: Set up Docker
      run: |
        docker build -t my-cpp-app .
    
    # Check if the image is built and healthy (without running the app)
    - name: Check Docker image health
      run: |
        docker images my-cpp-app
        # Optionally, check the image's health status if you have health checks in your Dockerfile
        # docker inspect --format='{{.State.Health.Status}}' my-cpp-app
